name: credentials

on: push

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Scans for secrets using truffleHog
      - uses: max/secret-scan@master
