name: credentials

on: push

jobs:
  check-credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: "Fetch all branches"
        run: |
          for remote in `git branch -r`; do git branch --track ${remote#origin/} $remote; done
          git checkout master
          git fetch --all
          git pull --all
          git checkout ${{ github.ref }}
          git branch
      # Scans for secrets using truffleHog
      - uses: max/secret-scan@master
